### ISSUE TITLE
Can we update more ghostblock?

### ISSUE THREAD

**Issue by GilloDaby** [gbl/AntiGhost#4]
Can we choose to update more block  like 50 block  around the player and not only like 5 /6 block in each direction? Thanks! I really need to be able to add more block to be rerender!

**Comment by gbl** [comment]
No, because that would cause a huge number of requests to the server. Right now, I'm requesting 4 blocks in each direction, which means 9 x 9 x 9 = 721 server requests. If you make this 50 - 25 each direction - you'd have 50*50*50=125000 requests. This would take many seconds, and if the server doesn't kick you immediately, cause massive load on the server.

Also, come on, you don't really need that many blocks. You won't detect a ghost block unless you're right next to it, so the 4 blocks each direction is already generous. A ghost block 20 blocks away won't affect you at all.

**Comment by GilloDaby** [comment]
And like 10 block in each direction is too much?

**Comment by GilloDaby** [comment]
BEcause will printer in litematica not all the block are unghosting so 8 or 10 will be correct :/

**Comment by gbl** [comment]
That'd still be way more, putting a heavy load on the server, and the last thing I'd want is people making an anti-antighost module in NoCheatPlus or anything because of it. AntiGhost is just not the tool to clear up massive amounts of ghost blocks caused by other mods.

**Comment by GilloDaby** [comment]
Yeah fine!
